### ISSUE TITLE
Customise using defined colors

### ISSUE THREAD

**Issue by gabrielelana** [sjrmanning/darkokai#3]
Hi, I would like to customise some of the git-gutter faces but I would like to use the theme defined colors

Ex. I would like to have the the _foreground_ of `git-gutter:added` green and for that I would like to use the already defined `darkokai-green` and for the _background_ use `darkokai-bg`

Is that possible in some way?

**Comment by sjrmanning** [comment]
Hey,

This wasn't actually possible because of the way the colours were defined (only temporary inside the `let*`), but I've refactored this to use a macro instead containing all the colour definitions, `darkokai-with-color-vars`.

This way, you can access `darkokai-green` or any other theme colour inside that macro. e.g.:

``` elisp
(darkokai-with-color-vars
  (set-face-foreground 'company-tooltip-common darkokai-magenta))
```

Hope that helps!

**Comment by gabrielelana** [comment]
That's perfect, thanks! 👍 🙇

**Comment by sjrmanning** [comment]
No problem! ☺️
